### REST Client extentions for vscode
### USER
// user:admin, token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI1ZmRjZmNlYzViM2U5ZjZjOGUwM2I2MjgiLCJuYW1lIjoiYWRtaW4iLCJzdXJuYW1lIjoiYWRtaW4iLCJuaWNrIjoiYWRtaW5TdXBlciIsImVtYWlsIjoiYWRtaW5AYWRtaW4uY29tIiwicm9sZSI6IlJPTEVfVVNFUiIsImltYWdlIjoiWXBsWkV2dDBsNkJUbGRrY1E0d1F4b1J5LmpwZyIsImlhdCI6MTYwODUwMjUyMSwiZXhwIjoxNjExMDk0NTIxfQ.F7gMSBo_MVunJ8eXqdKzbzvUl8a8CXvisvXe-JK-wJw

### publications
GET http://localhost:3800/api/publications
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI1ZmRjZmNlYzViM2U5ZjZjOGUwM2I2MjgiLCJuYW1lIjoiYWRtaW4iLCJzdXJuYW1lIjoiYWRtaW4iLCJuaWNrIjoiYWRtaW5TdXBlciIsImVtYWlsIjoiYWRtaW5AYWRtaW4uY29tIiwicm9sZSI6IlJPTEVfVVNFUiIsImltYWdlIjoiWXBsWkV2dDBsNkJUbGRrY1E0d1F4b1J5LmpwZyIsImlhdCI6MTYwODUwMjUyMSwiZXhwIjoxNjExMDk0NTIxfQ.F7gMSBo_MVunJ8eXqdKzbzvUl8a8CXvisvXe-JK-wJw

### nueva publication
POST http://localhost:3800/api/publication
Content-Type: application/json,
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI1ZmRjZmNlYzViM2U5ZjZjOGUwM2I2MjgiLCJuYW1lIjoiYWRtaW4iLCJzdXJuYW1lIjoiYWRtaW4iLCJuaWNrIjoiYWRtaW5TdXBlciIsImVtYWlsIjoiYWRtaW5AYWRtaW4uY29tIiwicm9sZSI6IlJPTEVfVVNFUiIsImltYWdlIjoiWXBsWkV2dDBsNkJUbGRrY1E0d1F4b1J5LmpwZyIsImlhdCI6MTYwODUwMjUyMSwiZXhwIjoxNjExMDk0NTIxfQ.F7gMSBo_MVunJ8eXqdKzbzvUl8a8CXvisvXe-JK-wJw
# esto de aqui es un request body
{
    // datos requeridos
    "text": "new publication"
}

### eliminado una publicacion
DELETE http://localhost:3800/api/publication/5fdd4c2dc995e82efddd6923
Content-Type: application/json,
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI1ZmRjZmNlYzViM2U5ZjZjOGUwM2I2MjgiLCJuYW1lIjoiYWRtaW4iLCJzdXJuYW1lIjoiYWRtaW4iLCJuaWNrIjoiYWRtaW5TdXBlciIsImVtYWlsIjoiYWRtaW5AYWRtaW4uY29tIiwicm9sZSI6IlJPTEVfVVNFUiIsImltYWdlIjoiWXBsWkV2dDBsNkJUbGRrY1E0d1F4b1J5LmpwZyIsImlhdCI6MTYwODUwMjUyMSwiZXhwIjoxNjExMDk0NTIxfQ.F7gMSBo_MVunJ8eXqdKzbzvUl8a8CXvisvXe-JK-wJw

