### REST Client extentions for vscode
### USER
// user:admin, token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI1ZmRjZmNlYzViM2U5ZjZjOGUwM2I2MjgiLCJuYW1lIjoiYWRtaW4iLCJzdXJuYW1lIjoiYWRtaW4iLCJuaWNrIjoiYWRtaW5TdXBlciIsImVtYWlsIjoiYWRtaW5AYWRtaW4uY29tIiwicm9sZSI6IlJPTEVfVVNFUiIsImltYWdlIjoiWXBsWkV2dDBsNkJUbGRrY1E0d1F4b1J5LmpwZyIsImlhdCI6MTYwODUwMjUyMSwiZXhwIjoxNjExMDk0NTIxfQ.F7gMSBo_MVunJ8eXqdKzbzvUl8a8CXvisvXe-JK-wJw

### nueva usuario
POST http://localhost:3800/api/register
Content-Type: application/json

# esto de aqui abajo es un request body
{
    // este es el campo requerido
    "name": "user4",
    "surname": "user4",
    "nick": "user4",
    "email": "user4@user4.com",
    "password": "admin"
}

### publications
GET http://localhost:3800/api/publications
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI1ZmRjZmNlYzViM2U5ZjZjOGUwM2I2MjgiLCJuYW1lIjoiYWRtaW4iLCJzdXJuYW1lIjoiYWRtaW4iLCJuaWNrIjoiYWRtaW5TdXBlciIsImVtYWlsIjoiYWRtaW5AYWRtaW4uY29tIiwicm9sZSI6IlJPTEVfVVNFUiIsImltYWdlIjoiWXBsWkV2dDBsNkJUbGRrY1E0d1F4b1J5LmpwZyIsImlhdCI6MTYwODUwMjUyMSwiZXhwIjoxNjExMDk0NTIxfQ.F7gMSBo_MVunJ8eXqdKzbzvUl8a8CXvisvXe-JK-wJw

### nueva publication
POST http://localhost:3800/api/publication
Content-Type: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI1ZmRjZmNlYzViM2U5ZjZjOGUwM2I2MjgiLCJuYW1lIjoiYWRtaW4iLCJzdXJuYW1lIjoiYWRtaW4iLCJuaWNrIjoiYWRtaW5TdXBlciIsImVtYWlsIjoiYWRtaW5AYWRtaW4uY29tIiwicm9sZSI6IlJPTEVfVVNFUiIsImltYWdlIjoiWXBsWkV2dDBsNkJUbGRrY1E0d1F4b1J5LmpwZyIsImlhdCI6MTYwODUwMjUyMSwiZXhwIjoxNjExMDk0NTIxfQ.F7gMSBo_MVunJ8eXqdKzbzvUl8a8CXvisvXe-JK-wJw

# esto de aqui abajo es un request body
{
    // este es el campo requerido
    "text": "new publication vscode"
}

### subir imagen de una publicación
POST http://localhost:3800/api/upload-image-pub/5fe2380a02917fbaa483f426
Content-Type: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI1ZmRjZmNlYzViM2U5ZjZjOGUwM2I2MjgiLCJuYW1lIjoiYWRtaW4iLCJzdXJuYW1lIjoiYWRtaW4iLCJuaWNrIjoiYWRtaW5TdXBlciIsImVtYWlsIjoiYWRtaW5AYWRtaW4uY29tIiwicm9sZSI6IlJPTEVfVVNFUiIsImltYWdlIjoiWXBsWkV2dDBsNkJUbGRrY1E0d1F4b1J5LmpwZyIsImlhdCI6MTYwODUwMjUyMSwiZXhwIjoxNjExMDk0NTIxfQ.F7gMSBo_MVunJ8eXqdKzbzvUl8a8CXvisvXe-JK-wJw

# esto de aqui abajo es un request body
{
    // este es la imagen requerida
    "image": "chef.jpg"
}


### eliminado una publicacion
DELETE http://localhost:3800/api/publication/5fdd4c2dc995e82efddd6923
Content-Type: application/json,
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI1ZmRjZmNlYzViM2U5ZjZjOGUwM2I2MjgiLCJuYW1lIjoiYWRtaW4iLCJzdXJuYW1lIjoiYWRtaW4iLCJuaWNrIjoiYWRtaW5TdXBlciIsImVtYWlsIjoiYWRtaW5AYWRtaW4uY29tIiwicm9sZSI6IlJPTEVfVVNFUiIsImltYWdlIjoiWXBsWkV2dDBsNkJUbGRrY1E0d1F4b1J5LmpwZyIsImlhdCI6MTYwODUwMjUyMSwiZXhwIjoxNjExMDk0NTIxfQ.F7gMSBo_MVunJ8eXqdKzbzvUl8a8CXvisvXe-JK-wJw

